#!/usr/bin/env python3
"""
Convert a markdown file to styled HTML.

Usage:
  python scripts/yt/build_html.py INPUT.md [-o OUTPUT.html]

Outputs HTML path to stdout on success.
"""

import argparse
import sys
from pathlib import Path

import markdown

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="{lang_attr}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  @page {{
    size: A4;
    margin: 2cm;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    font-family: "Noto Sans TC", "Microsoft JhengHei", "PingFang TC",
                 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    line-height: 1.7;
    color: #1a1a1a;
    max-width: 900px;
    margin: 0 auto;
    padding: 2rem;
    background: #fff;
  }}
  h1 {{
    font-size: 1.6rem;
    border-bottom: 3px solid #2563eb;
    padding-bottom: 0.4rem;
    margin-top: 2rem;
    color: #1e40af;
  }}
  h2 {{
    font-size: 1.2rem;
    color: #374151;
    margin-top: 1.5rem;
  }}
  h3 {{
    font-size: 1.05rem;
    color: #4b5563;
  }}
  a {{ color: #2563eb; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  ul, ol {{ padding-left: 1.5rem; }}
  li {{ margin-bottom: 0.3rem; }}
  blockquote {{
    border-left: 3px solid #2563eb;
    margin: 1rem 0;
    padding: 0.5rem 1rem;
    background: #f8fafc;
    color: #374151;
  }}
  img {{
    max-width: 100%;
    height: auto;
    border-radius: 8px;
    margin: 1rem 0;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  }}
  .video-thumbnail {{
    display: block;
    max-width: 640px;
    margin: 0.5rem auto 1.5rem;
  }}
  .footer {{
    text-align: center;
    color: #9ca3af;
    font-size: 0.85rem;
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid #e5e7eb;
  }}
</style>
</head>
<body>
{body}
<div class="footer">
  Generated by AI Daily Brief YT Digest
</div>
</body>
</html>
"""


def build_html(md_path: Path, title: str = "", lang: str = "en") -> str:
    """Convert a markdown file to styled HTML string."""
    md_text = md_path.read_text(encoding="utf-8")

    if not title:
        first_line = md_text.split("\n")[0]
        import re
        title = re.sub(r"^#+\s*", "", first_line).strip() or md_path.stem

    lang_attr = "zh-Hant" if "zh" in lang else "en"

    md_ext = markdown.Markdown(extensions=["tables", "fenced_code"])
    html_body = md_ext.convert(md_text)

    return HTML_TEMPLATE.format(
        lang_attr=lang_attr,
        title=title,
        body=html_body,
    )


def main():
    parser = argparse.ArgumentParser(description="Convert markdown to styled HTML")
    parser.add_argument("md_file", help="Input markdown file")
    parser.add_argument("-o", "--output", default=None, help="Output HTML path")
    parser.add_argument("--title", default="", help="Document title")
    parser.add_argument("--lang", default="en", help="Language: en or zh-tw")
    args = parser.parse_args()

    md_path = Path(args.md_file)
    if not md_path.exists():
        print(f"Error: {md_path} not found", file=sys.stderr)
        sys.exit(1)

    html = build_html(md_path, title=args.title, lang=args.lang)

    out_path = Path(args.output) if args.output else md_path.with_suffix(".html")
    out_path.write_text(html, encoding="utf-8")
    print(str(out_path))


if __name__ == "__main__":
    main()
